### ISSUE TITLE
[Feature / sulbao] 양조장체험 프로그램 등록

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/final-sulbao#11]
## 📜 Description

판매자가 양조장체험 프로그램을 운영하는경우 프로그램 정보를 등록하는 기능

## 🌈 Success criteria

- [ ] 프로그램명, 가격, 설명, 위치등  필수정보를 입력하지 않은 경우 에러메세지가 표시된다.
- [ ] DB에 프로그램정보가 등록된다.
- [ ] 등록에 성공한경우 등록에 성공했습니다. 메세지가 표시된다.
- [ ] 등록성공메세지 확인 버튼 누르면 프로그램 목록페이지로 이동한다.

## 👷 To-do

- [ ] 양조장체험 프로그램 등록화면 작성
- [ ] DB에 프로그램정보가 등록
- [ ] 필수 입력내용 입력체크

##  🔗Related issues

Related to: #이슈번호
