### ISSUE TITLE
[Feature / sulbao] 회원 메인 화면 구현

### ISSUE THREAD

**Issue by DISNOTACAT** [ssg-240304-java2/final-sulbao#118]
## 📜 Description
anonymous / member 권한에서 접속 가능한 메인 화면 구현

## 🌈 Success criteria
- [ ] 권한에 따라 헤더의 내용이 변경
- [ ] 전체 레이아웃 적용

## 👷 To-do
- [ ] 헤더 및 푸터에 술기로운 한잔 적용
- [ ] 각 버튼이 해당 페이지로 연결

##  🔗Related issues

Related to: #이슈번호
