### ISSUE TITLE
[Feature / sulbao] 선물 선결제

### ISSUE THREAD

**Issue by leejeonghun99** [ssg-240304-java2/final-sulbao#14]
## 📜 Description

결제 정보를 입력 받고 주소 입력 링크를 사용자에게 전달한다.

## 🌈 Success criteria

- [x] 사용자는 선물 물품에 대해 결제가 가능합니다.
- [x] 결제 완료 시 사용자에게 주문 확인서 메일과 주소지 입력 링크 메일을 전송합니다.
- [x] 결제 완료 시 상품의 상태는 주문 완료로 변경됩니다.
- [x] 결제 완료 시 주문 목록에 해당 상품이 추가됩니다.

## 👷 To-do

- [x] 구매 목록 표시
- [x] 상품명 클릭 시 상품 상세 페이지 이동
- [x] 선물 선결제 버튼 클릭 시 결제 정보 입력 페이지로 이동
- [x] 결제 완료 시 메일 전송

##  🔗Related issues

Related to: #이슈번호
