### ISSUE TITLE
[Feature / sulbao] (판매자)상품 상태변경

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/final-sulbao#156]
## 📜 Description

판매자가 등록한 상품 삭제, 진열상태, 판매여부 변경

## 🌈 Success criteria

- [x] 목록에서 선택한 상품이 삭제된다.
- [x] 목록에서 선택한 상품의 진열상태가 변경된다.
- [x] 목록에서 선택한 상품의 판매여부가 변경된다.

## 👷 To-do

- [x] 목록에 체크박스 추가
- [x] 목록에 있는 체크박스 모두 선택시  전체체크 박스 선택, 한개라도 해제되면 해제
- [x] 목록에서 체크한 상품삭제
- [x] 목록에서 체크한 진열상태 변경
- [x] 목록에서 체크한 판매여부 변경

##  🔗Related issues

Related to: #이슈번호
