### ISSUE TITLE
[Feature / sulbao] (회원) 상품 상세 조회

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/final-sulbao#159]
## 📜 Description

쇼핑몰 별  상품정보를 표시

## 🌈 Success criteria

- [ ] 선택한 상품 정보가 화면에 표시됩니다
- [ ] 상품수량에따라 합산된 금액이 화면에 표시됩니다.
- [ ] 장바구니 버튼 클릭시 장바구니로 이동하시겠습니까라는 메세지 표시되고 취소누르면 화면에 있습니다.

## 👷 To-do

- [ ] 상품 상세페이지 화면 개발
- [ ] 상품 수량 변경시 최종가격 변경
- [ ] 장바구니 버튼 클릭시 장바구니 이동 내용 메세지 표시

##  🔗Related issues

Related to: #이슈번호
