### ISSUE TITLE
[Feature / sulbao](관리자) 한 술매거진 등록/수정

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/final-sulbao#165]
## 📜 Description

한 술 매거진 내용이 등록된다.

## 🌈 Success criteria

- [ ] 필수정보 미입력시 에러메세지가 표시된다.
- [ ] 한술 매거진 등록정보가 등록됩니다.

## 👷 To-do

- [ ] 등록화면 개발
- [ ] 필수입력체크 기능개발
- [ ] 입력정보 저장
- [ ] 등록하신 한술매거진 정보 표시
- [ ] 등록하신 한술 매서진 정보 수정

##  🔗Related issues

Related to: #이슈번호
