### ISSUE TITLE
[Feature / sulbao] (관리자)한술매거진 삭제

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/final-sulbao#167]
## 📜 Description

목록에서 선택한 한술매거진이 삭제된다.

## 🌈 Success criteria

- [x] 선택한 한술매거진이 삭제됩니다.

## 👷 To-do

- [x] 목록화면에 체크박스 추가
- [x] 선택한 체크박스의 한술매거진 정보가 삭제

##  🔗Related issues

Related to: #이슈번호
