### ISSUE TITLE
[Feature / sulbao] 선물 배송지 등록

### ISSUE THREAD

**Issue by leejeonghun99** [ssg-240304-java2/final-sulbao#17]
## 📜 Description

선물 주소 입력 링크로 접속 시 회원가입 유무와 관계 없이 주소 입력 페이지로 이동하고
주소 입력 페이지에서 주소 정보를 입력받은 후 배송하기 버튼을 클릭 시 제품 상태가 주문 접수 상태로 변경됩니다.

## 🌈 Success criteria

- [ ] 해당 링크에서는 제품 정보를 가지고 있어 주문 제품 목록을 확인 가능합니다.
- [ ] 제품 정보에서 가격은 미 표기 합니다.
- [ ] 주소지를 입력하고 배송하기 버튼을 누르면 제품 상태가 주문 접수 완료 페이지로 이동합니다.

## 👷 To-do

- [ ] 페이지에서 선물받은 제품 목록을 볼 수가 있습니다.
- [ ] 배송주소 입력 페이지에서 주소지 입력
- [ ] 배송하기 버튼 클릭 시 제품의 상태 주문 접수 상태로 변경

##  🔗Related issues

Related to: #이슈번호
