### ISSUE TITLE
[Feature / sulbao] 양조장 체험 프로그램 취소(판매자) - 작성중

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/final-sulbao#23]
## 📜 Description

판매자가 회원이 취소한 프로그램 내용을 조회합니다.

## 🌈 Success criteria

- [ ] 회원, 프로그램으로 조회된 리스트가 표시된다.
- [ ] 예약번호 클릭 예약사유 및 예약정보가 표시된다.

## 👷 To-do

- [ ] 조회 및 검색 영역의 화면을 작성한다.
- [ ] 

##  🔗Related issues

Related to: #이슈번호
