### ISSUE TITLE
[Feature / sulbao] 최저가 비교 상품 등록 요청

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/final-sulbao#244]
## 📜 Description

판매자가 관리자에게 최저가비교 상품을 추가요청하는 기능입니다.
상품 등록 시 검색한 상품이 없을 경우 관리자에게 최저가 비교상품 군을 추가하도록 요청하는 기능입니다.

## 👷 To-do

- [ ] 판매자 상품 등록 시 최저가 비교 상품 select box 선택에서 조회로 변경
- [ ] 판매자가 원하는 상품이 없는 경우 "최저가 상품 등록을 요청하시겠습니까?" 라는 메세지가 표시되도록 수정
- [ ] 모달로 최저가 상품 등록 요청하는 팝업창이 표시되고 등록 할 수 있다.
    - [ ] 상품명, 상품 카테고리, 상품 상세정보 등록

## 🌈 Success criteria

- [ ] 최저가  비교상품에 상품명을 입력할때마다 검색결과가 하단에 실시간으로 변동될것
- [ ] 등록되지 않은 상품명을 입력한경우 "최저가 상품 등록을 요청하시겠습니까?" 라는 메세지가 표시될것
- [ ] "최저가 상품 등록을 요청하시겠습니까?" 메세지 클릭시 상품등록 모달창이 표시될것
- [ ] 최저가상품등록 완료시 관리자 승인을 기다려주세요 라는 화면표시후 목록으로 이동될것

##  🔗Related issues

Related to: #이슈번호
