### ISSUE TITLE
[Feature / sulbao] 세금 계산서 발행

### ISSUE THREAD

**Issue by leejeonghun99** [ssg-240304-java2/final-sulbao#35]
## 📜 Description

관리자는 판매자별 판매 목록 조회 및 매월 초 판매 금액 별 세금 계산서를 조회 및 이를 판매자에게 전송한다.

## 🌈 Success criteria

- [ ] 관리자는 구매 확정에 대한 목록을 조회 가능하다
- [ ] 관리자는 판매자 별 구매 확정에 대한 목록 조회 가능하다.
- [ ] 관리자는 매월 판매자별 구매 확정에 대한 목록 조회가 가능하다.
- [ ] 관리자는 판매자별 매월 판매 세금서를 지정된 세금 계산 양식에 따라 조회 가능하다.

## 👷 To-do

- [ ] 관리자는 구매 확정 목록에 따른 전체 테이블 조회가 가능
- [ ] 관리자는 카테고리로 판매자별, 월별 목록 조회가 가능
- [ ] 월별은 매월 1일을 정산 기준으로 정한다.
- [ ] 관리자는 매달 판매자별 판매 세금계산서를 조회 가능하다.

##  🔗Related issues

Related to: #이슈번호
