### ISSUE TITLE
[Feature / sulbao]

### ISSUE THREAD

**Issue by gusrbstjr** [ssg-240304-java2/final-sulbao#36]
## 📜 Description

등록된 상품의 재고 수량 수정 기능 구현
## 🌈 Success criteria

1. 상품의 재고 수량을 수정
2. DB에 상품 재고 수량을 수정
3. 품절 상태일때 재고가 들어왔을 경우 재입고 알림 등록한 회원에게 알림 발송
## 👷 To-do

- [ ] 수량 수정 버튼 추가
- [ ] 입력 받은 정보를 DB에 저장
- [ ] 재입고 알림 발송
##  🔗Related issues

Related to: #이슈번호
