### ISSUE TITLE
[Feature / sulbao] 양조장 체험 프로그램 수정

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/final-sulbao#38]
## 📜 Description

판매자와 관리자가 양조장 체험 프로그램정보를 수정을 하는경우 
프로그램을 아직 참여안한 회원들에게 메일이 발송됩니다.

## 🌈 Success criteria

- [ ] 양조장 체험 프로그램 정보를 수정할 경우 회원에게 메일이 발생된다.
- [ ] 양조장 체험 프로그램 정보 수정을 취소할 경우 회원에게 메일이 발송되지 않는다.
- [ ] 발송된 메일 정보가 DB에 저장된다.

## 👷 To-do

- [ ] 양조장 체험 프로그램 수정 화면 개발
- [ ] 양조장 체험 프로그램 필수입력 필드 입력체크
- [ ] 수정하기 버튼 클릭시 수정하시겠습니까? 메세지가 표시된다.
- [ ] 필수입력 필드에게 값이 있는경우  수정을 진행한다.

##  🔗Related issues

Related to: #이슈번호
