### ISSUE TITLE
[Feature / sulbao] 양조장 체험 프로그램 삭제

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/final-sulbao#39]
## 📜 Description

판매자 또는 관리자가 프로그램을 삭제하는기능

## 🌈 Success criteria

- [ ] 삭제버튼 클릭시 체험프로그램이 삭제됩니다.
- [ ] 프로그램을 신청한 회원이 있는경우 예약상태를 예약취소로 변경하고, 프로그램 취소로 인한 예약취소를 안내하는 메일을 발송한다.

## 👷 To-do

- [ ] 양조장 체험 프로그램 수정 페이지 하단에 삭제버튼 추가
- [ ] 삭제시 삭제하시겠습니까? 안내메세지 표시
- [ ] DB에서 삭제 플래그 true로 변경

##  🔗Related issues

Related to: #이슈번호
