### ISSUE TITLE
[Feature / sulbao] 구매 확정

### ISSUE THREAD

**Issue by leejeonghun99** [ssg-240304-java2/final-sulbao#5]
## 📜 Description

회원이 구매 확정 버튼을 눌렀을 때 상품 상태가 구매 확정 상태로 변경된다.

## 🌈 Success criteria

- [ ] 회원의 아이디를 통해 구매한 상품 목록을 조회 합니다.
- [ ] 상품 목록 중 제품의 상태가 구매 확정이 아닌 상품에는 구매 확정 버튼이 표기 됩니다.
- [ ] 구매 확정 버튼 클릭 시 해당 제품에 대한 포인트가 적립 됩니다.
- [ ] 구매 확정 버튼 클릭 시 제품 상태가 구매 확정 상태로 변경됩니다.
## 👷 To-do

- [ ] 구매한 상품 목록 조회
- [ ] 상품명 클릭 시 제품 페이지로 이동
- [ ] 구매 확정 버튼 클릭 시 사용자 포인트 누적 및 제품 상태 변경
##  🔗Related issues

Related to: #이슈번호
