### ISSUE TITLE
[Feature / sulbao] 회원 등록

### ISSUE THREAD

**Issue by DISNOTACAT** [ssg-240304-java2/final-sulbao#50]
## 📜 Description

성인인증 완료 후 회원가입 폼을 기준으로 계정 데이터 저장

## 🌈 Success criteria

1. 성인인증 성공 값 저장
2. 필수 입력 조건을 통과한 회원가입 폼기준 계정 데이터 저장

## 👷 To-do

- [x] bbaton 성인인증 API 테스트
- [x] 회원가입 양식 및 필수 입력 조건 설정
- [x] 계정 데이터 저장

##  🔗Related issues

Related to: #이슈번호
