### ISSUE TITLE
[Feature / sulbao] 계정 권한별 로그인

### ISSUE THREAD

**Issue by DISNOTACAT** [ssg-240304-java2/final-sulbao#51]
## 📜 Description

회원, 판매자, 관리자 권한으로 나뉘어 저장된 계정 데이터로 로그인

## 🌈 Success criteria

1. 회원 권한으로 접속시 쇼핑몰 연결
2. 판매자 권한으로 접속시 입점사 대시보드 연결
3. 관리자 권한으로 접속시 관리자 대시보드 연결

## 👷 To-do

- [x] 회원 권한으로 로그인
- [x] 판매자 권한으로 로그인
- [x] 관리자 권한으로 로그인
- [x] 로그인 오류시 알림창

##  🔗Related issues

Related to: #이슈번호

**Comment by DISNOTACAT** [comment]
권한별 config 추가가 필요합니다. 다른 기능 개발 후 시간 여유 있을 때 수정하겠습니다.
권한 및 로그인 처리에는 이상 없습니다.
