### ISSUE TITLE
[Feature / sulbao] 입점신청

### ISSUE THREAD

**Issue by DISNOTACAT** [ssg-240304-java2/final-sulbao#52]
## 📜 Description

사업자번호를 포함한 필수 입력 조건을 통과한 입점 신청서 데이터 저장

## 🌈 Success criteria

1. 사업자번호 검증 완료
2. 필수 입력 조건을 통과한 회원가입 폼기준 계정 데이터 전달

## 👷 To-do

- [x] 입점 신청서 양식 및 필수 입력 조건 설정
- [x] 사업자 번호 중복 검사 완료
- [x] 이메일 중복 및 본인 인증 검사 완료
- [x] 아이디 중복 검사 완료
- [x] 입점 신청서 데이터 저장

##  🔗Related issues

Related to: #이슈번호
